import datetime
import json
import os
import streamlit as st

#### %%writefile must be the first line in the cell to work properly in Jupyter. This command creates a new file.
##########################################################
########### CREATION OF THE STREAMLIT DASHBOARD ##########
##########################################################
### app.py - This is the Streamlit application that serves as the executive dashboard for the RegTech surveillance system. 
### It displays the AI-generated bilingual report and key metrics from the latest surveillance run.


# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="RegTech AI Surveillance",
    page_icon="🛡️",
    layout="wide",
    initial_sidebar_state="expanded"
)

# --- HEADER ---
st.title("🛡️ RegTech Automated Surveillance System")
st.markdown("### Executive Regulatory Intelligence Dashboard")
st.markdown("---")

# --- SIMULATED DATA INGESTION ---
# In production, this would fetch from your SQLAlchemy 'RegulatoryReport' table
# For this MVP frontend, we load the JSON payload directly.
@st.cache_data
def load_mock_data():
    return {
        "execution_date": datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "total_alerts": 12,
        "english_summary": """
• **Change #1 (MODIFIED)** in URL: https://www.ema.europa.eu/en/human-regulatory-overview
  • Summary: The volumes of the rules governing medicinal products in the EU have been updated from 1-4 and 9-10 to 2-5 and 9-11.\n
• **Change #4 (MODIFIED)** in URL: https://www.ema.europa.eu/en/human-regulatory-overview/clinical-trials
  • Summary: The initial advice for sponsors on clinical trials was issued on 15 March 2025.
        """,
        "spanish_summary": """
• **Cambio #1 (MODIFICADO)** en URL: https://www.ema.europa.eu/es/human-regulatory-overview
  • Resumen: Los volúmenes de las reglas que rigen los productos medicinales en la UE han sido actualizados a 2-5 y 9-11.\n
• **Cambio #4 (MODIFICADO)** en URL: https://www.ema.europa.eu/es/human-regulatory-overview/clinical-trials
  • Resumen: El consejo inicial para los patrocinadores sobre ensayos clínicos se emitió el 15 de marzo de 2025.
        """
    }

report_data = load_mock_data()

# --- SIDEBAR CONTROLS ---
with st.sidebar:
    st.header("⚙️ Dashboard Controls")
    language = st.radio("Select Report Language / Idioma:", ("English", "Español"))
    st.markdown("---")
    st.metric(label="Target Source", value="EMA Guidelines")
    st.metric(label="Last Execution", value=report_data["execution_date"])
    st.metric(label="Critical Alerts Detected", value=report_data["total_alerts"])

# --- MAIN DASHBOARD AREA ---
col1, col2 = st.columns([2, 1])

with col1:
    st.subheader(f"📑 AI Executive Summary ({language})")
    st.info("Report generated by Groq Cloud (Llama 3.1) based on hybrid NLP diffs.")

    if language == "English":
        st.markdown(report_data["english_summary"])
    else:
        st.markdown(report_data["spanish_summary"])

with col2:
    st.subheader("📊 System Status")
    st.success("✅ Baseline Synchronized")
    st.success("✅ NLP Engine Online")
    st.success("✅ Database Committed")

    st.markdown("### Next Steps")
    st.button("Run Scenario 3 Verification", type="primary", use_container_width=True)

st.markdown("---")
st.caption("Developed by Juan Álvaro Romero | Ironhack Big Data & Machine Learning MVP | © 2026")
